import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider, SignedIn, SignedOut } from "@clerk/nextjs";
import { Navbar } from "@/components/Navbar";
import { ThemeProvider } from "@/components/theme-provider"
import { Toaster } from 'sonner'



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en" className={`${geistSans.variable} ${geistMono.variable} suppressHydrationWarning` }>
        <body className="">
        <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
          <Navbar/>
          <div className="max-w-7xl  mx-auto">
            {children}
            <Toaster />
          </div>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
